[package]
name = "gaming_limousin"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dotenv = "0.15.0"
env_logger = "0.11.5"
log = "0.4.22"
poise = "0.6.1"
tokio = { version = "1.40", features = ["full"] }
